### ISSUE TITLE
Possible array overflow in  bl602_glb.c

### ISSUE THREAD

**Issue by qarmin** [pine64/bl_iot_sdk#38]
https://github.com/pine64/bl_iot_sdk/blob/eba302dc8550e01d89f8510ed8ca470d766d4b88/components/bl602/bl602_std/bl602_std/StdDriver/Src/bl602_glb.c#L71
have only 23 elements but it can be accessed at 24 - 32 index
https://github.com/pine64/bl_iot_sdk/blob/eba302dc8550e01d89f8510ed8ca470d766d4b88/components/bl602/bl602_std/bl602_std/StdDriver/Src/bl602_glb.c#L2352-L2354

**Comment by gamelaster** [comment]
Hi,
Please, can you make fix in PR?
Thanks
