### ISSUE TITLE
Unused sampling variable, due to assigning data to self in dac_audio.c

### ISSUE THREAD

**Issue by qarmin** [pine64/bl_iot_sdk#40]
https://github.com/pine64/bl_iot_sdk/blob/eba302dc8550e01d89f8510ed8ca470d766d4b88/customer_app/sdk_app_dac/sdk_app_dac/dac_audio.c#L211-L213

**Comment by robertlipe** [comment]
I'll fix that. Stand by.

**Comment by robertlipe** [comment]
https://github.com/pine64/bl_iot_sdk/pull/47 cleans this up.

I hopped on it because this was code I'd stared at yesterday.
