### ISSUE TITLE
Sleep modes samples

### ISSUE THREAD

**Issue by DurandA** [pine64/bl_iot_sdk#69]
Has anyone played with the sleep modes (Idle Power Saving Mode and Sleep Mode)?

I just received a board and I am looking to measure current (using a [uCurrent](https://www.eevblog.com/projects/ucurrent/)) in the various modes.

**Comment by YafeiJin** [comment]
@DurandA wifi connected or not?

**Comment by DurandA** [comment]
I'm mostly interested in deep sleep but will measure other modes as well. I am not sure what low power modes are compatible with keeping the WiFi.

**Comment by YafeiJin** [comment]
Okey, it is simple.
Hibernate: Only wake up by GPIOs in Alway-on-Domain, and RTC, <0.5uA@3.3v
PDS7: Wake up by most GPIOs, and RTC, <12uA@3.3v

**Comment by DurandA** [comment]
@YafeiJin Thank you. I see that you are working for Bouffalo Lab, thank you for your involvement with the open-source community.

Do you also have some power figures when scaling the CPU clock? Also can you elaborate on the use of PDS2? According to the manual the CPU power domain is off but the WiFi/BLE PHY/MAC are enabled. Can this be used to maintain the WiFi connection while the CPU is sleeping?

**Comment by YafeiJin** [comment]
@DurandA For CPU part, 22mA@192MHz, 2mA@<10MHz; 
Yes, it's doable. But commonly, it will be involved many custom development.

**Comment by DurandA** [comment]
@YafeiJin Thank you.
