### ISSUE TITLE
USB-C power sink implementation on the PineCone is wrong

### ISSUE THREAD

**Issue by ProZsolt** [pine64/bl_iot_sdk#74]
If [this](https://www.cnx-software.com/pdf/schematics/Pine64%20BL602%20EVB%20Schematic%20ver%201.1.pdf) is the correct schematic for the PineCone then you made the same mistake as the Rasberry Pi 4. Connected the two CC lines and only used one pulldown resistor. According to spec, you have to use two separate resistors. For more information see [Benson Leung's post](https://medium.com/@leung.benson/how-to-design-a-proper-usb-c-power-sink-hint-not-the-way-raspberry-pi-4-did-it-f470d7a5910)

**Comment by gamelaster** [comment]
Hi, thank you for letting us know. This issue was already reported and it will be fixed in next design revision.

**Comment by WildCryptoFox** [comment]
For reference which batch round would this be?

**Comment by gamelaster** [comment]
All (1K) PineCones are affected (It was reported too late to be fixed in this batch). It will be fixed in next batch.
